### ISSUE TITLE
When deconvolving, Python<3.11 will throw a TypeError due to changed behaviour of `warnings`

### ISSUE THREAD

**Issue by OfAaron3** [OfAaron3/irispreppy#8]
Essentially, Python>=3.11 has a keyword `action` included in `warnings.catch_warnings()`, this is not present in older versions of Python. The error will be,

`TypeError: __init__() got an unexpected keyword argument 'action'`

I plan to do some tests to figure out which method of ignoring warnings works on older (as old as 3.83) and newer (>=3.11) versions. I am currently away on a work trip, so I will be unable to dig too deeply until I am back next week.
